"""create core ride pooling tables

Revision ID: 6e8dc0ba1150
Revises: 
Create Date: 2026-09-28 19:24:18.170204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8dc0ba1150'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PASSENGER', 'DRIVER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('zones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ride_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('passenger_id', sa.Uuid(), nullable=False),
    sa.Column('pickup_zone_id', sa.Uuid(), nullable=False),
    sa.Column('destination_zone_id', sa.Uuid(), nullable=False),
    sa.Column('seats_requested', sa.Integer(), nullable=False),
    sa.Column('estimated_fare_paisa', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'MATCHED', 'DRIVER_ARRIVED', 'STARTED', 'COMPLETED', 'CANCELLED', name='ridestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('estimated_fare_paisa >= 0', name='check_ride_fare_non_negative'),
    sa.CheckConstraint('seats_requested > 0', name='check_ride_seats_positive'),
    sa.ForeignKeyConstraint(['destination_zone_id'], ['zones.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pickup_zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_requests_passenger_id'), 'ride_requests', ['passenger_id'], unique=False)
    op.create_index(op.f('ix_ride_requests_status'), 'ride_requests', ['status'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity > 0', name='check_vehicle_capacity_positive'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_driver_id'), 'vehicles', ['driver_id'], unique=False)
    op.create_table('pools',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='poolstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pools_status'), 'pools', ['status'], unique=False)
    op.create_index(op.f('ix_pools_vehicle_id'), 'pools', ['vehicle_id'], unique=False)
    op.create_table('ride_status_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ride_request_id', sa.Uuid(), nullable=False),
    sa.Column('old_status', sa.Enum('REQUESTED', 'MATCHED', 'DRIVER_ARRIVED', 'STARTED', 'COMPLETED', 'CANCELLED', name='ridestatus'), nullable=True),
    sa.Column('new_status', sa.Enum('REQUESTED', 'MATCHED', 'DRIVER_ARRIVED', 'STARTED', 'COMPLETED', 'CANCELLED', name='ridestatus'), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ride_request_id'], ['ride_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_status_history_ride_request_id'), 'ride_status_history', ['ride_request_id'], unique=False)
    op.create_table('pool_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pool_id', sa.Uuid(), nullable=False),
    sa.Column('ride_request_id', sa.Uuid(), nullable=False),
    sa.Column('seats_allocated', sa.Integer(), nullable=False),
    sa.Column('fare_paisa', sa.BigInteger(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fare_paisa >= 0', name='check_member_fare_non_negative'),
    sa.CheckConstraint('seats_allocated > 0', name='check_allocated_seats_positive'),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ),
    sa.ForeignKeyConstraint(['ride_request_id'], ['ride_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_id', 'ride_request_id', name='uq_pool_ride')
    )
    op.create_index(op.f('ix_pool_members_pool_id'), 'pool_members', ['pool_id'], unique=False)
    op.create_index(op.f('ix_pool_members_ride_request_id'), 'pool_members', ['ride_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pool_members_ride_request_id'), table_name='pool_members')
    op.drop_index(op.f('ix_pool_members_pool_id'), table_name='pool_members')
    op.drop_table('pool_members')
    op.drop_index(op.f('ix_ride_status_history_ride_request_id'), table_name='ride_status_history')
    op.drop_table('ride_status_history')
    op.drop_index(op.f('ix_pools_vehicle_id'), table_name='pools')
    op.drop_index(op.f('ix_pools_status'), table_name='pools')
    op.drop_table('pools')
    op.drop_index(op.f('ix_vehicles_driver_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_ride_requests_status'), table_name='ride_requests')
    op.drop_index(op.f('ix_ride_requests_passenger_id'), table_name='ride_requests')
    op.drop_table('ride_requests')
    op.drop_table('zones')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
